#!/bin/csh

tap R
set proj_path = /data/bswift-0/meyerct/emoprox/ctm_1mm_censor_5regs/
cd $proj_path
3dMEMA -prefix ../MEMA_res/VelocityXProximity_v_Background.nii.gz                      \
       -mask ../anatMask/multiMask_Apr22nd2016_30.nii                               \
       -set  velocityXprox                                                           \
         301                                                                        \
           subj301_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj301_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         302                                                                        \
           subj302_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj302_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         303                                                                        \
           subj303_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj303_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         304                                                                        \
           subj304_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj304_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         305                                                                        \
           subj305_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj305_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         306                                                                        \
           subj306_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj306_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         307                                                                        \
           subj307_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj307_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         308                                                                        \
           subj308_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj308_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         309                                                                        \
           subj309_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj309_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         310                                                                        \
           subj310_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj310_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         311                                                                        \
           subj311_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj311_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         312                                                                        \
           subj312_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj312_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         313                                                                        \
           subj313_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj313_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         314                                                                        \
           subj314_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj314_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         315                                                                        \
           subj315_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj315_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         316                                                                        \
           subj316_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj316_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         317                                                                        \
           subj317_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj317_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         318                                                                        \
           subj318_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj318_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         319                                                                        \
           subj319_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj319_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         320                                                                        \
           subj320_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj320_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         321                                                                        \
           subj321_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj321_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         322                                                                        \
           subj322_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj322_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         323                                                                        \
           subj323_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj323_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         324                                                                        \
           subj324_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj324_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         325                                                                        \
           subj325_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj325_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         326                                                                        \
           subj326_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj326_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         327                                                                        \
           subj327_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj327_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         328                                                                        \
           subj328_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj328_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         329                                                                        \
           subj329_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj329_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         330                                                                        \
           subj330_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj330_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         331                                                                        \
           subj331_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj331_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         332                                                                        \
           subj332_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj332_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         333                                                                        \
           subj333_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj333_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         334                                                                        \
           subj334_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj334_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         335                                                                        \
           subj335_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj335_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         336                                                                        \
           subj336_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj336_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         337                                                                        \
           subj337_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj337_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         338                                                                        \
           subj338_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj338_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         339                                                                        \
           subj339_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj339_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         340                                                                        \
           subj340_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj340_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         341                                                                        \
           subj341_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj341_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         342                                                                        \
           subj342_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj342_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         343                                                                        \
           subj343_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj343_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         344                                                                        \
           subj344_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj344_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         345                                                                        \
           subj345_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj345_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         346                                                                        \
           subj346_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj346_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         347                                                                        \
           subj347_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj347_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         348                                                                        \
           subj348_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj348_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         349                                                                        \
           subj349_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj349_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         350                                                                        \
           subj350_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj350_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         351                                                                        \
           subj351_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj351_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         352                                                                        \
           subj352_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj352_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         353                                                                        \
           subj353_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj353_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         354                                                                        \
           subj354_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj354_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         355                                                                        \
           subj355_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj355_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         356                                                                        \
           subj356_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj356_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         357                                                                        \
           subj357_Rstim_moshock_bucket_4runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj357_Rstim_moshock_bucket_4runs.nii.gz'[velocityXprox#0_Tstat]'         \
         358                                                                        \
           subj358_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj358_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         359                                                                        \
           subj359_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj359_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         360                                                                        \
           subj360_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj360_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         361                                                                        \
           subj361_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj361_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         362                                                                        \
           subj362_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj362_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         363                                                                        \
           subj363_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj363_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         364                                                                        \
           subj364_Rstim_moshock_bucket_12356runs.nii.gz'[velocityXprox#0_Coef]'     \
           subj364_Rstim_moshock_bucket_12356runs.nii.gz'[velocityXprox#0_Tstat]'     \
         366                                                                        \
           subj366_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj366_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         367                                                                        \
           subj367_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj367_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         368                                                                        \
           subj368_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj368_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         369                                                                        \
           subj369_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj369_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         370                                                                        \
           subj370_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj370_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         371                                                                        \
           subj371_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj371_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         372                                                                        \
           subj372_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj372_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         373                                                                        \
           subj373_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj373_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         374                                                                        \
           subj374_Rstim_moshock_bucket_4runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj374_Rstim_moshock_bucket_4runs.nii.gz'[velocityXprox#0_Tstat]'         \
         375                                                                        \
           subj375_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj375_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         376                                                                        \
           subj376_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj376_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         377                                                                        \
           subj377_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj377_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         378                                                                        \
           subj378_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj378_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         379                                                                        \
           subj379_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj379_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         380                                                                        \
           subj380_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj380_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         381                                                                        \
           subj381_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Coef]'         \
           subj381_Rstim_moshock_bucket_6runs.nii.gz'[velocityXprox#0_Tstat]'         \
         -jobs 4                              \
         -cio

cd ../scripts/
3drefit -overwrite -space MNI -xdel 2 -ydel 2 -zdel 2  -duporigin ./MNI152_T1_2mm.nii.gz ../MEMA_res/VelocityXProximity_v_Background.nii.gz                      \
